// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/common.proto

package ir

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeKind defines the high-level category of a type.
type TypeKind int32

const (
	TypeKind_TYPE_KIND_UNSPECIFIED TypeKind = 0
	TypeKind_TYPE_KIND_BASIC       TypeKind = 1 // int, float, bool, string, etc.
	TypeKind_TYPE_KIND_POINTER     TypeKind = 2
	TypeKind_TYPE_KIND_STRUCT      TypeKind = 3
	TypeKind_TYPE_KIND_ARRAY       TypeKind = 4
	TypeKind_TYPE_KIND_SLICE       TypeKind = 5
	TypeKind_TYPE_KIND_MAP         TypeKind = 6
	TypeKind_TYPE_KIND_INTERFACE   TypeKind = 7
	TypeKind_TYPE_KIND_FUNC        TypeKind = 8
	TypeKind_TYPE_KIND_CHAN        TypeKind = 9
	TypeKind_TYPE_KIND_TUPLE       TypeKind = 10 // Multiple return values
	TypeKind_TYPE_KIND_NAMED       TypeKind = 11 // Defined type (e.g. type MyInt int)
)

// Enum value maps for TypeKind.
var (
	TypeKind_name = map[int32]string{
		0:  "TYPE_KIND_UNSPECIFIED",
		1:  "TYPE_KIND_BASIC",
		2:  "TYPE_KIND_POINTER",
		3:  "TYPE_KIND_STRUCT",
		4:  "TYPE_KIND_ARRAY",
		5:  "TYPE_KIND_SLICE",
		6:  "TYPE_KIND_MAP",
		7:  "TYPE_KIND_INTERFACE",
		8:  "TYPE_KIND_FUNC",
		9:  "TYPE_KIND_CHAN",
		10: "TYPE_KIND_TUPLE",
		11: "TYPE_KIND_NAMED",
	}
	TypeKind_value = map[string]int32{
		"TYPE_KIND_UNSPECIFIED": 0,
		"TYPE_KIND_BASIC":       1,
		"TYPE_KIND_POINTER":     2,
		"TYPE_KIND_STRUCT":      3,
		"TYPE_KIND_ARRAY":       4,
		"TYPE_KIND_SLICE":       5,
		"TYPE_KIND_MAP":         6,
		"TYPE_KIND_INTERFACE":   7,
		"TYPE_KIND_FUNC":        8,
		"TYPE_KIND_CHAN":        9,
		"TYPE_KIND_TUPLE":       10,
		"TYPE_KIND_NAMED":       11,
	}
)

func (x TypeKind) Enum() *TypeKind {
	p := new(TypeKind)
	*p = x
	return p
}

func (x TypeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (TypeKind) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x TypeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeKind.Descriptor instead.
func (TypeKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

// BasicTypeKind refines TYPE_KIND_BASIC.
type BasicTypeKind int32

const (
	BasicTypeKind_BASIC_TYPE_KIND_UNSPECIFIED     BasicTypeKind = 0
	BasicTypeKind_BASIC_TYPE_KIND_BOOL            BasicTypeKind = 1
	BasicTypeKind_BASIC_TYPE_KIND_INT             BasicTypeKind = 2
	BasicTypeKind_BASIC_TYPE_KIND_INT8            BasicTypeKind = 3
	BasicTypeKind_BASIC_TYPE_KIND_INT16           BasicTypeKind = 4
	BasicTypeKind_BASIC_TYPE_KIND_INT32           BasicTypeKind = 5
	BasicTypeKind_BASIC_TYPE_KIND_INT64           BasicTypeKind = 6
	BasicTypeKind_BASIC_TYPE_KIND_UINT            BasicTypeKind = 7
	BasicTypeKind_BASIC_TYPE_KIND_UINT8           BasicTypeKind = 8
	BasicTypeKind_BASIC_TYPE_KIND_UINT16          BasicTypeKind = 9
	BasicTypeKind_BASIC_TYPE_KIND_UINT32          BasicTypeKind = 10
	BasicTypeKind_BASIC_TYPE_KIND_UINT64          BasicTypeKind = 11
	BasicTypeKind_BASIC_TYPE_KIND_UINTPTR         BasicTypeKind = 12
	BasicTypeKind_BASIC_TYPE_KIND_FLOAT32         BasicTypeKind = 13
	BasicTypeKind_BASIC_TYPE_KIND_FLOAT64         BasicTypeKind = 14
	BasicTypeKind_BASIC_TYPE_KIND_COMPLEX64       BasicTypeKind = 15
	BasicTypeKind_BASIC_TYPE_KIND_COMPLEX128      BasicTypeKind = 16
	BasicTypeKind_BASIC_TYPE_KIND_STRING          BasicTypeKind = 17
	BasicTypeKind_BASIC_TYPE_KIND_UNSAFE_POINTER  BasicTypeKind = 18
	BasicTypeKind_BASIC_TYPE_KIND_UNTYPED_BOOL    BasicTypeKind = 19
	BasicTypeKind_BASIC_TYPE_KIND_UNTYPED_INT     BasicTypeKind = 20
	BasicTypeKind_BASIC_TYPE_KIND_UNTYPED_RUNE    BasicTypeKind = 21
	BasicTypeKind_BASIC_TYPE_KIND_UNTYPED_FLOAT   BasicTypeKind = 22
	BasicTypeKind_BASIC_TYPE_KIND_UNTYPED_COMPLEX BasicTypeKind = 23
	BasicTypeKind_BASIC_TYPE_KIND_UNTYPED_STRING  BasicTypeKind = 24
	BasicTypeKind_BASIC_TYPE_KIND_UNTYPED_NIL     BasicTypeKind = 25
)

// Enum value maps for BasicTypeKind.
var (
	BasicTypeKind_name = map[int32]string{
		0:  "BASIC_TYPE_KIND_UNSPECIFIED",
		1:  "BASIC_TYPE_KIND_BOOL",
		2:  "BASIC_TYPE_KIND_INT",
		3:  "BASIC_TYPE_KIND_INT8",
		4:  "BASIC_TYPE_KIND_INT16",
		5:  "BASIC_TYPE_KIND_INT32",
		6:  "BASIC_TYPE_KIND_INT64",
		7:  "BASIC_TYPE_KIND_UINT",
		8:  "BASIC_TYPE_KIND_UINT8",
		9:  "BASIC_TYPE_KIND_UINT16",
		10: "BASIC_TYPE_KIND_UINT32",
		11: "BASIC_TYPE_KIND_UINT64",
		12: "BASIC_TYPE_KIND_UINTPTR",
		13: "BASIC_TYPE_KIND_FLOAT32",
		14: "BASIC_TYPE_KIND_FLOAT64",
		15: "BASIC_TYPE_KIND_COMPLEX64",
		16: "BASIC_TYPE_KIND_COMPLEX128",
		17: "BASIC_TYPE_KIND_STRING",
		18: "BASIC_TYPE_KIND_UNSAFE_POINTER",
		19: "BASIC_TYPE_KIND_UNTYPED_BOOL",
		20: "BASIC_TYPE_KIND_UNTYPED_INT",
		21: "BASIC_TYPE_KIND_UNTYPED_RUNE",
		22: "BASIC_TYPE_KIND_UNTYPED_FLOAT",
		23: "BASIC_TYPE_KIND_UNTYPED_COMPLEX",
		24: "BASIC_TYPE_KIND_UNTYPED_STRING",
		25: "BASIC_TYPE_KIND_UNTYPED_NIL",
	}
	BasicTypeKind_value = map[string]int32{
		"BASIC_TYPE_KIND_UNSPECIFIED":     0,
		"BASIC_TYPE_KIND_BOOL":            1,
		"BASIC_TYPE_KIND_INT":             2,
		"BASIC_TYPE_KIND_INT8":            3,
		"BASIC_TYPE_KIND_INT16":           4,
		"BASIC_TYPE_KIND_INT32":           5,
		"BASIC_TYPE_KIND_INT64":           6,
		"BASIC_TYPE_KIND_UINT":            7,
		"BASIC_TYPE_KIND_UINT8":           8,
		"BASIC_TYPE_KIND_UINT16":          9,
		"BASIC_TYPE_KIND_UINT32":          10,
		"BASIC_TYPE_KIND_UINT64":          11,
		"BASIC_TYPE_KIND_UINTPTR":         12,
		"BASIC_TYPE_KIND_FLOAT32":         13,
		"BASIC_TYPE_KIND_FLOAT64":         14,
		"BASIC_TYPE_KIND_COMPLEX64":       15,
		"BASIC_TYPE_KIND_COMPLEX128":      16,
		"BASIC_TYPE_KIND_STRING":          17,
		"BASIC_TYPE_KIND_UNSAFE_POINTER":  18,
		"BASIC_TYPE_KIND_UNTYPED_BOOL":    19,
		"BASIC_TYPE_KIND_UNTYPED_INT":     20,
		"BASIC_TYPE_KIND_UNTYPED_RUNE":    21,
		"BASIC_TYPE_KIND_UNTYPED_FLOAT":   22,
		"BASIC_TYPE_KIND_UNTYPED_COMPLEX": 23,
		"BASIC_TYPE_KIND_UNTYPED_STRING":  24,
		"BASIC_TYPE_KIND_UNTYPED_NIL":     25,
	}
)

func (x BasicTypeKind) Enum() *BasicTypeKind {
	p := new(BasicTypeKind)
	*p = x
	return p
}

func (x BasicTypeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BasicTypeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (BasicTypeKind) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x BasicTypeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BasicTypeKind.Descriptor instead.
func (BasicTypeKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

// Position represents a source code location.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Position) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Type represents a type in the IR.
type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  TypeKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=godzilla.ir.v1.TypeKind" json:"kind,omitempty"`
	// Only set if kind == TYPE_KIND_BASIC
	BasicKind BasicTypeKind `protobuf:"varint,2,opt,name=basic_kind,json=basicKind,proto3,enum=godzilla.ir.v1.BasicTypeKind" json:"basic_kind,omitempty"`
	// Only set if kind == TYPE_KIND_POINTER, ARRAY, SLICE, CHAN, MAP (key/elem)
	ElemType *Type `protobuf:"bytes,3,opt,name=elem_type,json=elemType,proto3" json:"elem_type,omitempty"`
	KeyType  *Type `protobuf:"bytes,4,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"` // For maps
	// Only set if kind == TYPE_KIND_ARRAY
	ArrayLen int64 `protobuf:"varint,5,opt,name=array_len,json=arrayLen,proto3" json:"array_len,omitempty"`
	// Only set if kind == TYPE_KIND_STRUCT
	Fields []*Field `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	// Only set if kind == TYPE_KIND_INTERFACE
	Methods []*Method `protobuf:"bytes,7,rep,name=methods,proto3" json:"methods,omitempty"`
	// Only set if kind == TYPE_KIND_FUNC
	Signature *Signature `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	// Only set if kind == TYPE_KIND_NAMED
	Name           string    `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	UnderlyingType *Type     `protobuf:"bytes,10,opt,name=underlying_type,json=underlyingType,proto3" json:"underlying_type,omitempty"` // The underlying type definition
	MethodSet      []*Method `protobuf:"bytes,11,rep,name=method_set,json=methodSet,proto3" json:"method_set,omitempty"`                // Methods associated with this named type
	Pos            *Position `protobuf:"bytes,12,opt,name=pos,proto3" json:"pos,omitempty"`                                             // Definition position for named types
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *Type) GetKind() TypeKind {
	if x != nil {
		return x.Kind
	}
	return TypeKind_TYPE_KIND_UNSPECIFIED
}

func (x *Type) GetBasicKind() BasicTypeKind {
	if x != nil {
		return x.BasicKind
	}
	return BasicTypeKind_BASIC_TYPE_KIND_UNSPECIFIED
}

func (x *Type) GetElemType() *Type {
	if x != nil {
		return x.ElemType
	}
	return nil
}

func (x *Type) GetKeyType() *Type {
	if x != nil {
		return x.KeyType
	}
	return nil
}

func (x *Type) GetArrayLen() int64 {
	if x != nil {
		return x.ArrayLen
	}
	return 0
}

func (x *Type) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Type) GetMethods() []*Method {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Type) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetUnderlyingType() *Type {
	if x != nil {
		return x.UnderlyingType
	}
	return nil
}

func (x *Type) GetMethodSet() []*Method {
	if x != nil {
		return x.MethodSet
	}
	return nil
}

func (x *Type) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

// Field represents a struct field.
type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`            // Struct tag (e.g. for Go/JSON)
	Embedded      bool                   `protobuf:"varint,4,opt,name=embedded,proto3" json:"embedded,omitempty"` // Anonymous field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Field) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Field) GetEmbedded() bool {
	if x != nil {
		return x.Embedded
	}
	return false
}

// Method represents a method in an interface or named type.
type Method struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Signature     *Type                  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Must be TYPE_KIND_FUNC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Method) Reset() {
	*x = Method{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Method) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method) ProtoMessage() {}

func (x *Method) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method.ProtoReflect.Descriptor instead.
func (*Method) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *Method) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Method) GetSignature() *Type {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Signature represents a function signature.
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*Type                `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	Results       []*Type                `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Variadic      bool                   `protobuf:"varint,3,opt,name=variadic,proto3" json:"variadic,omitempty"`
	Recv          *Type                  `protobuf:"bytes,4,opt,name=recv,proto3" json:"recv,omitempty"` // Receiver type (for methods), optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *Signature) GetParams() []*Type {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Signature) GetResults() []*Type {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Signature) GetVariadic() bool {
	if x != nil {
		return x.Variadic
	}
	return false
}

func (x *Signature) GetRecv() *Type {
	if x != nil {
		return x.Recv
	}
	return nil
}

// Constant represents a literal value.
type Constant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  *Type                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Constant_BoolVal
	//	*Constant_IntVal
	//	*Constant_FloatVal
	//	*Constant_StringVal
	Value         isConstant_Value `protobuf_oneof:"value"`
	IsNil         bool             `protobuf:"varint,6,opt,name=is_nil,json=isNil,proto3" json:"is_nil,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constant) Reset() {
	*x = Constant{}
	mi := &file_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constant) ProtoMessage() {}

func (x *Constant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constant.ProtoReflect.Descriptor instead.
func (*Constant) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *Constant) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Constant) GetValue() isConstant_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Constant) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Value.(*Constant_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

func (x *Constant) GetIntVal() int64 {
	if x != nil {
		if x, ok := x.Value.(*Constant_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *Constant) GetFloatVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*Constant_FloatVal); ok {
			return x.FloatVal
		}
	}
	return 0
}

func (x *Constant) GetStringVal() string {
	if x != nil {
		if x, ok := x.Value.(*Constant_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

func (x *Constant) GetIsNil() bool {
	if x != nil {
		return x.IsNil
	}
	return false
}

type isConstant_Value interface {
	isConstant_Value()
}

type Constant_BoolVal struct {
	BoolVal bool `protobuf:"varint,2,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type Constant_IntVal struct {
	IntVal int64 `protobuf:"varint,3,opt,name=int_val,json=intVal,proto3,oneof"` // Store all integers as 64-bit
}

type Constant_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,4,opt,name=float_val,json=floatVal,proto3,oneof"` // Store all floats as double
}

type Constant_StringVal struct {
	StringVal string `protobuf:"bytes,5,opt,name=string_val,json=stringVal,proto3,oneof"` // Complex numbers can be stored as real/imag parts if needed, omitting for brevity
}

func (*Constant_BoolVal) isConstant_Value() {}

func (*Constant_IntVal) isConstant_Value() {}

func (*Constant_FloatVal) isConstant_Value() {}

func (*Constant_StringVal) isConstant_Value() {}

// Global represents a global variable.
type Global struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	InitValue     *Constant              `protobuf:"bytes,3,opt,name=init_value,json=initValue,proto3" json:"init_value,omitempty"` // Optional initialization value
	Pos           *Position              `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Global) Reset() {
	*x = Global{}
	mi := &file_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global) ProtoMessage() {}

func (x *Global) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global.ProtoReflect.Descriptor instead.
func (*Global) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *Global) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Global) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Global) GetInitValue() *Constant {
	if x != nil {
		return x.InitValue
	}
	return nil
}

func (x *Global) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x0egodzilla.ir.v1\"R\n" +
	"\bPosition\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"\xc3\x04\n" +
	"\x04Type\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.godzilla.ir.v1.TypeKindR\x04kind\x12<\n" +
	"\n" +
	"basic_kind\x18\x02 \x01(\x0e2\x1d.godzilla.ir.v1.BasicTypeKindR\tbasicKind\x121\n" +
	"\telem_type\x18\x03 \x01(\v2\x14.godzilla.ir.v1.TypeR\belemType\x12/\n" +
	"\bkey_type\x18\x04 \x01(\v2\x14.godzilla.ir.v1.TypeR\akeyType\x12\x1b\n" +
	"\tarray_len\x18\x05 \x01(\x03R\barrayLen\x12-\n" +
	"\x06fields\x18\x06 \x03(\v2\x15.godzilla.ir.v1.FieldR\x06fields\x120\n" +
	"\amethods\x18\a \x03(\v2\x16.godzilla.ir.v1.MethodR\amethods\x127\n" +
	"\tsignature\x18\b \x01(\v2\x19.godzilla.ir.v1.SignatureR\tsignature\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12=\n" +
	"\x0funderlying_type\x18\n" +
	" \x01(\v2\x14.godzilla.ir.v1.TypeR\x0eunderlyingType\x125\n" +
	"\n" +
	"method_set\x18\v \x03(\v2\x16.godzilla.ir.v1.MethodR\tmethodSet\x12*\n" +
	"\x03pos\x18\f \x01(\v2\x18.godzilla.ir.v1.PositionR\x03pos\"s\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\v2\x14.godzilla.ir.v1.TypeR\x04type\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x1a\n" +
	"\bembedded\x18\x04 \x01(\bR\bembedded\"P\n" +
	"\x06Method\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.godzilla.ir.v1.TypeR\tsignature\"\xaf\x01\n" +
	"\tSignature\x12,\n" +
	"\x06params\x18\x01 \x03(\v2\x14.godzilla.ir.v1.TypeR\x06params\x12.\n" +
	"\aresults\x18\x02 \x03(\v2\x14.godzilla.ir.v1.TypeR\aresults\x12\x1a\n" +
	"\bvariadic\x18\x03 \x01(\bR\bvariadic\x12(\n" +
	"\x04recv\x18\x04 \x01(\v2\x14.godzilla.ir.v1.TypeR\x04recv\"\xcc\x01\n" +
	"\bConstant\x12(\n" +
	"\x04type\x18\x01 \x01(\v2\x14.godzilla.ir.v1.TypeR\x04type\x12\x1b\n" +
	"\bbool_val\x18\x02 \x01(\bH\x00R\aboolVal\x12\x19\n" +
	"\aint_val\x18\x03 \x01(\x03H\x00R\x06intVal\x12\x1d\n" +
	"\tfloat_val\x18\x04 \x01(\x01H\x00R\bfloatVal\x12\x1f\n" +
	"\n" +
	"string_val\x18\x05 \x01(\tH\x00R\tstringVal\x12\x15\n" +
	"\x06is_nil\x18\x06 \x01(\bR\x05isNilB\a\n" +
	"\x05value\"\xab\x01\n" +
	"\x06Global\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\v2\x14.godzilla.ir.v1.TypeR\x04type\x127\n" +
	"\n" +
	"init_value\x18\x03 \x01(\v2\x18.godzilla.ir.v1.ConstantR\tinitValue\x12*\n" +
	"\x03pos\x18\x04 \x01(\v2\x18.godzilla.ir.v1.PositionR\x03pos*\x8f\x02\n" +
	"\bTypeKind\x12\x19\n" +
	"\x15TYPE_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTYPE_KIND_BASIC\x10\x01\x12\x15\n" +
	"\x11TYPE_KIND_POINTER\x10\x02\x12\x14\n" +
	"\x10TYPE_KIND_STRUCT\x10\x03\x12\x13\n" +
	"\x0fTYPE_KIND_ARRAY\x10\x04\x12\x13\n" +
	"\x0fTYPE_KIND_SLICE\x10\x05\x12\x11\n" +
	"\rTYPE_KIND_MAP\x10\x06\x12\x17\n" +
	"\x13TYPE_KIND_INTERFACE\x10\a\x12\x12\n" +
	"\x0eTYPE_KIND_FUNC\x10\b\x12\x12\n" +
	"\x0eTYPE_KIND_CHAN\x10\t\x12\x13\n" +
	"\x0fTYPE_KIND_TUPLE\x10\n" +
	"\x12\x13\n" +
	"\x0fTYPE_KIND_NAMED\x10\v*\x9f\x06\n" +
	"\rBasicTypeKind\x12\x1f\n" +
	"\x1bBASIC_TYPE_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BASIC_TYPE_KIND_BOOL\x10\x01\x12\x17\n" +
	"\x13BASIC_TYPE_KIND_INT\x10\x02\x12\x18\n" +
	"\x14BASIC_TYPE_KIND_INT8\x10\x03\x12\x19\n" +
	"\x15BASIC_TYPE_KIND_INT16\x10\x04\x12\x19\n" +
	"\x15BASIC_TYPE_KIND_INT32\x10\x05\x12\x19\n" +
	"\x15BASIC_TYPE_KIND_INT64\x10\x06\x12\x18\n" +
	"\x14BASIC_TYPE_KIND_UINT\x10\a\x12\x19\n" +
	"\x15BASIC_TYPE_KIND_UINT8\x10\b\x12\x1a\n" +
	"\x16BASIC_TYPE_KIND_UINT16\x10\t\x12\x1a\n" +
	"\x16BASIC_TYPE_KIND_UINT32\x10\n" +
	"\x12\x1a\n" +
	"\x16BASIC_TYPE_KIND_UINT64\x10\v\x12\x1b\n" +
	"\x17BASIC_TYPE_KIND_UINTPTR\x10\f\x12\x1b\n" +
	"\x17BASIC_TYPE_KIND_FLOAT32\x10\r\x12\x1b\n" +
	"\x17BASIC_TYPE_KIND_FLOAT64\x10\x0e\x12\x1d\n" +
	"\x19BASIC_TYPE_KIND_COMPLEX64\x10\x0f\x12\x1e\n" +
	"\x1aBASIC_TYPE_KIND_COMPLEX128\x10\x10\x12\x1a\n" +
	"\x16BASIC_TYPE_KIND_STRING\x10\x11\x12\"\n" +
	"\x1eBASIC_TYPE_KIND_UNSAFE_POINTER\x10\x12\x12 \n" +
	"\x1cBASIC_TYPE_KIND_UNTYPED_BOOL\x10\x13\x12\x1f\n" +
	"\x1bBASIC_TYPE_KIND_UNTYPED_INT\x10\x14\x12 \n" +
	"\x1cBASIC_TYPE_KIND_UNTYPED_RUNE\x10\x15\x12!\n" +
	"\x1dBASIC_TYPE_KIND_UNTYPED_FLOAT\x10\x16\x12#\n" +
	"\x1fBASIC_TYPE_KIND_UNTYPED_COMPLEX\x10\x17\x12\"\n" +
	"\x1eBASIC_TYPE_KIND_UNTYPED_STRING\x10\x18\x12\x1f\n" +
	"\x1bBASIC_TYPE_KIND_UNTYPED_NIL\x10\x19B\x17Z\x15godzilla/pkg/ir/v1;irb\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_common_proto_goTypes = []any{
	(TypeKind)(0),      // 0: godzilla.ir.v1.TypeKind
	(BasicTypeKind)(0), // 1: godzilla.ir.v1.BasicTypeKind
	(*Position)(nil),   // 2: godzilla.ir.v1.Position
	(*Type)(nil),       // 3: godzilla.ir.v1.Type
	(*Field)(nil),      // 4: godzilla.ir.v1.Field
	(*Method)(nil),     // 5: godzilla.ir.v1.Method
	(*Signature)(nil),  // 6: godzilla.ir.v1.Signature
	(*Constant)(nil),   // 7: godzilla.ir.v1.Constant
	(*Global)(nil),     // 8: godzilla.ir.v1.Global
}
var file_proto_common_proto_depIdxs = []int32{
	0,  // 0: godzilla.ir.v1.Type.kind:type_name -> godzilla.ir.v1.TypeKind
	1,  // 1: godzilla.ir.v1.Type.basic_kind:type_name -> godzilla.ir.v1.BasicTypeKind
	3,  // 2: godzilla.ir.v1.Type.elem_type:type_name -> godzilla.ir.v1.Type
	3,  // 3: godzilla.ir.v1.Type.key_type:type_name -> godzilla.ir.v1.Type
	4,  // 4: godzilla.ir.v1.Type.fields:type_name -> godzilla.ir.v1.Field
	5,  // 5: godzilla.ir.v1.Type.methods:type_name -> godzilla.ir.v1.Method
	6,  // 6: godzilla.ir.v1.Type.signature:type_name -> godzilla.ir.v1.Signature
	3,  // 7: godzilla.ir.v1.Type.underlying_type:type_name -> godzilla.ir.v1.Type
	5,  // 8: godzilla.ir.v1.Type.method_set:type_name -> godzilla.ir.v1.Method
	2,  // 9: godzilla.ir.v1.Type.pos:type_name -> godzilla.ir.v1.Position
	3,  // 10: godzilla.ir.v1.Field.type:type_name -> godzilla.ir.v1.Type
	3,  // 11: godzilla.ir.v1.Method.signature:type_name -> godzilla.ir.v1.Type
	3,  // 12: godzilla.ir.v1.Signature.params:type_name -> godzilla.ir.v1.Type
	3,  // 13: godzilla.ir.v1.Signature.results:type_name -> godzilla.ir.v1.Type
	3,  // 14: godzilla.ir.v1.Signature.recv:type_name -> godzilla.ir.v1.Type
	3,  // 15: godzilla.ir.v1.Constant.type:type_name -> godzilla.ir.v1.Type
	3,  // 16: godzilla.ir.v1.Global.type:type_name -> godzilla.ir.v1.Type
	7,  // 17: godzilla.ir.v1.Global.init_value:type_name -> godzilla.ir.v1.Constant
	2,  // 18: godzilla.ir.v1.Global.pos:type_name -> godzilla.ir.v1.Position
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	file_proto_common_proto_msgTypes[5].OneofWrappers = []any{
		(*Constant_BoolVal)(nil),
		(*Constant_IntVal)(nil),
		(*Constant_FloatVal)(nil),
		(*Constant_StringVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
