// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/function.proto

package ir

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BasicBlock represents a sequence of instructions with single entry and exit.
type BasicBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"` // e.g. "entry", "cond.true"
	Instrs        []*Instruction         `protobuf:"bytes,3,rep,name=instrs,proto3" json:"instrs,omitempty"`
	Preds         []int32                `protobuf:"varint,4,rep,packed,name=preds,proto3" json:"preds,omitempty"` // Predecessor block indices
	Succs         []int32                `protobuf:"varint,5,rep,packed,name=succs,proto3" json:"succs,omitempty"` // Successor block indices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicBlock) Reset() {
	*x = BasicBlock{}
	mi := &file_proto_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicBlock) ProtoMessage() {}

func (x *BasicBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicBlock.ProtoReflect.Descriptor instead.
func (*BasicBlock) Descriptor() ([]byte, []int) {
	return file_proto_function_proto_rawDescGZIP(), []int{0}
}

func (x *BasicBlock) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BasicBlock) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *BasicBlock) GetInstrs() []*Instruction {
	if x != nil {
		return x.Instrs
	}
	return nil
}

func (x *BasicBlock) GetPreds() []int32 {
	if x != nil {
		return x.Preds
	}
	return nil
}

func (x *BasicBlock) GetSuccs() []int32 {
	if x != nil {
		return x.Succs
	}
	return nil
}

// Function represents a function definition.
type Function struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // Unique name within the frontend (e.g. main.main)
	ObjectName  string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`    // Original source name (e.g. main)
	MethodName  string                 `protobuf:"bytes,3,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`    // If method, the method name.
	PackageName string                 `protobuf:"bytes,4,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"` // Package path.
	Signature   *Signature             `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Pos         *Position              `protobuf:"bytes,6,opt,name=pos,proto3" json:"pos,omitempty"`
	Params      []*Value               `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty"`                     // Function parameters
	FreeVars    []*Value               `protobuf:"bytes,8,rep,name=free_vars,json=freeVars,proto3" json:"free_vars,omitempty"` // Captured variables (closure)
	Blocks      []*BasicBlock          `protobuf:"bytes,9,rep,name=blocks,proto3" json:"blocks,omitempty"`                     // Basic blocks forming the function body
	Locals      []*Value               `protobuf:"bytes,10,rep,name=locals,proto3" json:"locals,omitempty"`                    // Local variables (allocs) that might be lifted
	Parent      *Type                  `protobuf:"bytes,11,opt,name=parent,proto3" json:"parent,omitempty"`                    // If method, the receiver type
	Synthetic   bool                   `protobuf:"varint,12,opt,name=synthetic,proto3" json:"synthetic,omitempty"`             // True if generated by compiler/wrapper
	// Canonical fully-qualified name used by rules to match across languages.
	// Scheme: "<lang>:<module/path>.<Type>.<member>", e.g.
	//
	//	"go:net/http.(*Request).FormValue", "py:flask.request.args.get".
	CanonicalName string `protobuf:"bytes,13,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_proto_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_proto_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_proto_function_proto_rawDescGZIP(), []int{1}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *Function) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *Function) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Function) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Function) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Function) GetParams() []*Value {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Function) GetFreeVars() []*Value {
	if x != nil {
		return x.FreeVars
	}
	return nil
}

func (x *Function) GetBlocks() []*BasicBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Function) GetLocals() []*Value {
	if x != nil {
		return x.Locals
	}
	return nil
}

func (x *Function) GetParent() *Type {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Function) GetSynthetic() bool {
	if x != nil {
		return x.Synthetic
	}
	return false
}

func (x *Function) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

var File_proto_function_proto protoreflect.FileDescriptor

const file_proto_function_proto_rawDesc = "" +
	"\n" +
	"\x14proto/function.proto\x12\x0egodzilla.ir.v1\x1a\x12proto/common.proto\x1a\x17proto/instruction.proto\"\x9d\x01\n" +
	"\n" +
	"BasicBlock\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x123\n" +
	"\x06instrs\x18\x03 \x03(\v2\x1b.godzilla.ir.v1.InstructionR\x06instrs\x12\x14\n" +
	"\x05preds\x18\x04 \x03(\x05R\x05preds\x12\x14\n" +
	"\x05succs\x18\x05 \x03(\x05R\x05succs\"\xa1\x04\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName\x12\x1f\n" +
	"\vmethod_name\x18\x03 \x01(\tR\n" +
	"methodName\x12!\n" +
	"\fpackage_name\x18\x04 \x01(\tR\vpackageName\x127\n" +
	"\tsignature\x18\x05 \x01(\v2\x19.godzilla.ir.v1.SignatureR\tsignature\x12*\n" +
	"\x03pos\x18\x06 \x01(\v2\x18.godzilla.ir.v1.PositionR\x03pos\x12-\n" +
	"\x06params\x18\a \x03(\v2\x15.godzilla.ir.v1.ValueR\x06params\x122\n" +
	"\tfree_vars\x18\b \x03(\v2\x15.godzilla.ir.v1.ValueR\bfreeVars\x122\n" +
	"\x06blocks\x18\t \x03(\v2\x1a.godzilla.ir.v1.BasicBlockR\x06blocks\x12-\n" +
	"\x06locals\x18\n" +
	" \x03(\v2\x15.godzilla.ir.v1.ValueR\x06locals\x12,\n" +
	"\x06parent\x18\v \x01(\v2\x14.godzilla.ir.v1.TypeR\x06parent\x12\x1c\n" +
	"\tsynthetic\x18\f \x01(\bR\tsynthetic\x12%\n" +
	"\x0ecanonical_name\x18\r \x01(\tR\rcanonicalNameB\x17Z\x15godzilla/pkg/ir/v1;irb\x06proto3"

var (
	file_proto_function_proto_rawDescOnce sync.Once
	file_proto_function_proto_rawDescData []byte
)

func file_proto_function_proto_rawDescGZIP() []byte {
	file_proto_function_proto_rawDescOnce.Do(func() {
		file_proto_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_function_proto_rawDesc), len(file_proto_function_proto_rawDesc)))
	})
	return file_proto_function_proto_rawDescData
}

var file_proto_function_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_function_proto_goTypes = []any{
	(*BasicBlock)(nil),  // 0: godzilla.ir.v1.BasicBlock
	(*Function)(nil),    // 1: godzilla.ir.v1.Function
	(*Instruction)(nil), // 2: godzilla.ir.v1.Instruction
	(*Signature)(nil),   // 3: godzilla.ir.v1.Signature
	(*Position)(nil),    // 4: godzilla.ir.v1.Position
	(*Value)(nil),       // 5: godzilla.ir.v1.Value
	(*Type)(nil),        // 6: godzilla.ir.v1.Type
}
var file_proto_function_proto_depIdxs = []int32{
	2, // 0: godzilla.ir.v1.BasicBlock.instrs:type_name -> godzilla.ir.v1.Instruction
	3, // 1: godzilla.ir.v1.Function.signature:type_name -> godzilla.ir.v1.Signature
	4, // 2: godzilla.ir.v1.Function.pos:type_name -> godzilla.ir.v1.Position
	5, // 3: godzilla.ir.v1.Function.params:type_name -> godzilla.ir.v1.Value
	5, // 4: godzilla.ir.v1.Function.free_vars:type_name -> godzilla.ir.v1.Value
	0, // 5: godzilla.ir.v1.Function.blocks:type_name -> godzilla.ir.v1.BasicBlock
	5, // 6: godzilla.ir.v1.Function.locals:type_name -> godzilla.ir.v1.Value
	6, // 7: godzilla.ir.v1.Function.parent:type_name -> godzilla.ir.v1.Type
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_function_proto_init() }
func file_proto_function_proto_init() {
	if File_proto_function_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_instruction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_function_proto_rawDesc), len(file_proto_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_function_proto_goTypes,
		DependencyIndexes: file_proto_function_proto_depIdxs,
		MessageInfos:      file_proto_function_proto_msgTypes,
	}.Build()
	File_proto_function_proto = out.File
	file_proto_function_proto_goTypes = nil
	file_proto_function_proto_depIdxs = nil
}
