// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/instruction.proto

package ir

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpCode defines the operation to perform.
//
// gIR v2 keeps a deliberately SMALL, language-neutral core. Anything specific to
// a source language (Go channels/defer/goroutines/select, Python magic methods,
// JS dynamic property access, language builtins, ...) is expressed as an
// OP_CODE_INTRINSIC carrying a canonical `intrinsic` name that the analysis
// engine and rules interpret. Adding a language must NOT require new opcodes.
type OpCode int32

const (
	OpCode_OP_CODE_UNSPECIFIED OpCode = 0
	// Basic Block Terminators
	OpCode_OP_CODE_RET         OpCode = 1
	OpCode_OP_CODE_JUMP        OpCode = 2
	OpCode_OP_CODE_IF          OpCode = 3
	OpCode_OP_CODE_SWITCH      OpCode = 4
	OpCode_OP_CODE_PANIC       OpCode = 5 // abnormal termination / throw
	OpCode_OP_CODE_UNREACHABLE OpCode = 6
	// Memory Operations
	OpCode_OP_CODE_ALLOC OpCode = 10
	OpCode_OP_CODE_LOAD  OpCode = 11
	OpCode_OP_CODE_STORE OpCode = 12
	// Aggregate access
	OpCode_OP_CODE_FIELD      OpCode = 13 // struct/object field read (by index)
	OpCode_OP_CODE_FIELD_ADDR OpCode = 14 // address of a struct/object field
	OpCode_OP_CODE_INDEX      OpCode = 15 // array/slice/string element read
	OpCode_OP_CODE_INDEX_ADDR OpCode = 16 // address of an array/slice element
	// Arithmetic / Logic
	OpCode_OP_CODE_BIN_OP OpCode = 20
	OpCode_OP_CODE_UN_OP  OpCode = 21
	OpCode_OP_CODE_PHI    OpCode = 22 // SSA phi node
	// Calls
	OpCode_OP_CODE_CALL   OpCode = 30 // statically-resolved call
	OpCode_OP_CODE_INVOKE OpCode = 31 // dynamic / virtual dispatch (interface, vtable)
	// Type operations
	OpCode_OP_CODE_CONVERT        OpCode = 40 // numeric/string conversion, cast, change-type/interface
	OpCode_OP_CODE_TYPE_ASSERT    OpCode = 41
	OpCode_OP_CODE_MAKE_INTERFACE OpCode = 42 // box a concrete value into an interface / any
	OpCode_OP_CODE_EXTRACT        OpCode = 43 // extract element i from a tuple (multi-value result)
	// Escape hatch: any language-specific operation, named by `intrinsic`.
	// e.g. "go.chan.send", "go.defer", "go.map.update", "builtin.make_closure",
	//
	//	"py.attr.get", "js.property.get". Operands/call carry its arguments.
	OpCode_OP_CODE_INTRINSIC OpCode = 50
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0:  "OP_CODE_UNSPECIFIED",
		1:  "OP_CODE_RET",
		2:  "OP_CODE_JUMP",
		3:  "OP_CODE_IF",
		4:  "OP_CODE_SWITCH",
		5:  "OP_CODE_PANIC",
		6:  "OP_CODE_UNREACHABLE",
		10: "OP_CODE_ALLOC",
		11: "OP_CODE_LOAD",
		12: "OP_CODE_STORE",
		13: "OP_CODE_FIELD",
		14: "OP_CODE_FIELD_ADDR",
		15: "OP_CODE_INDEX",
		16: "OP_CODE_INDEX_ADDR",
		20: "OP_CODE_BIN_OP",
		21: "OP_CODE_UN_OP",
		22: "OP_CODE_PHI",
		30: "OP_CODE_CALL",
		31: "OP_CODE_INVOKE",
		40: "OP_CODE_CONVERT",
		41: "OP_CODE_TYPE_ASSERT",
		42: "OP_CODE_MAKE_INTERFACE",
		43: "OP_CODE_EXTRACT",
		50: "OP_CODE_INTRINSIC",
	}
	OpCode_value = map[string]int32{
		"OP_CODE_UNSPECIFIED":    0,
		"OP_CODE_RET":            1,
		"OP_CODE_JUMP":           2,
		"OP_CODE_IF":             3,
		"OP_CODE_SWITCH":         4,
		"OP_CODE_PANIC":          5,
		"OP_CODE_UNREACHABLE":    6,
		"OP_CODE_ALLOC":          10,
		"OP_CODE_LOAD":           11,
		"OP_CODE_STORE":          12,
		"OP_CODE_FIELD":          13,
		"OP_CODE_FIELD_ADDR":     14,
		"OP_CODE_INDEX":          15,
		"OP_CODE_INDEX_ADDR":     16,
		"OP_CODE_BIN_OP":         20,
		"OP_CODE_UN_OP":          21,
		"OP_CODE_PHI":            22,
		"OP_CODE_CALL":           30,
		"OP_CODE_INVOKE":         31,
		"OP_CODE_CONVERT":        40,
		"OP_CODE_TYPE_ASSERT":    41,
		"OP_CODE_MAKE_INTERFACE": 42,
		"OP_CODE_EXTRACT":        43,
		"OP_CODE_INTRINSIC":      50,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_instruction_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_proto_instruction_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_instruction_proto_rawDescGZIP(), []int{0}
}

// BinOpKind defines binary operators.
type BinOpKind int32

const (
	BinOpKind_BIN_OP_UNSPECIFIED BinOpKind = 0
	BinOpKind_BIN_OP_ADD         BinOpKind = 1
	BinOpKind_BIN_OP_SUB         BinOpKind = 2
	BinOpKind_BIN_OP_MUL         BinOpKind = 3
	BinOpKind_BIN_OP_QUO         BinOpKind = 4
	BinOpKind_BIN_OP_REM         BinOpKind = 5
	BinOpKind_BIN_OP_AND         BinOpKind = 6
	BinOpKind_BIN_OP_OR          BinOpKind = 7
	BinOpKind_BIN_OP_XOR         BinOpKind = 8
	BinOpKind_BIN_OP_SHL         BinOpKind = 9
	BinOpKind_BIN_OP_SHR         BinOpKind = 10
	BinOpKind_BIN_OP_AND_NOT     BinOpKind = 11
	BinOpKind_BIN_OP_EQL         BinOpKind = 12
	BinOpKind_BIN_OP_NEQ         BinOpKind = 13
	BinOpKind_BIN_OP_LSS         BinOpKind = 14
	BinOpKind_BIN_OP_LEQ         BinOpKind = 15
	BinOpKind_BIN_OP_GTR         BinOpKind = 16
	BinOpKind_BIN_OP_GEQ         BinOpKind = 17
)

// Enum value maps for BinOpKind.
var (
	BinOpKind_name = map[int32]string{
		0:  "BIN_OP_UNSPECIFIED",
		1:  "BIN_OP_ADD",
		2:  "BIN_OP_SUB",
		3:  "BIN_OP_MUL",
		4:  "BIN_OP_QUO",
		5:  "BIN_OP_REM",
		6:  "BIN_OP_AND",
		7:  "BIN_OP_OR",
		8:  "BIN_OP_XOR",
		9:  "BIN_OP_SHL",
		10: "BIN_OP_SHR",
		11: "BIN_OP_AND_NOT",
		12: "BIN_OP_EQL",
		13: "BIN_OP_NEQ",
		14: "BIN_OP_LSS",
		15: "BIN_OP_LEQ",
		16: "BIN_OP_GTR",
		17: "BIN_OP_GEQ",
	}
	BinOpKind_value = map[string]int32{
		"BIN_OP_UNSPECIFIED": 0,
		"BIN_OP_ADD":         1,
		"BIN_OP_SUB":         2,
		"BIN_OP_MUL":         3,
		"BIN_OP_QUO":         4,
		"BIN_OP_REM":         5,
		"BIN_OP_AND":         6,
		"BIN_OP_OR":          7,
		"BIN_OP_XOR":         8,
		"BIN_OP_SHL":         9,
		"BIN_OP_SHR":         10,
		"BIN_OP_AND_NOT":     11,
		"BIN_OP_EQL":         12,
		"BIN_OP_NEQ":         13,
		"BIN_OP_LSS":         14,
		"BIN_OP_LEQ":         15,
		"BIN_OP_GTR":         16,
		"BIN_OP_GEQ":         17,
	}
)

func (x BinOpKind) Enum() *BinOpKind {
	p := new(BinOpKind)
	*p = x
	return p
}

func (x BinOpKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinOpKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_instruction_proto_enumTypes[1].Descriptor()
}

func (BinOpKind) Type() protoreflect.EnumType {
	return &file_proto_instruction_proto_enumTypes[1]
}

func (x BinOpKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinOpKind.Descriptor instead.
func (BinOpKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_instruction_proto_rawDescGZIP(), []int{1}
}

// UnOpKind defines unary operators.
type UnOpKind int32

const (
	UnOpKind_UN_OP_UNSPECIFIED UnOpKind = 0
	UnOpKind_UN_OP_NOT         UnOpKind = 1 // !x
	UnOpKind_UN_OP_BIT_NOT     UnOpKind = 2 // ^x
	UnOpKind_UN_OP_NEG         UnOpKind = 3 // -x
	UnOpKind_UN_OP_POS         UnOpKind = 4 // +x
	UnOpKind_UN_OP_ADDR        UnOpKind = 5 // &x
	UnOpKind_UN_OP_DEREF       UnOpKind = 6 // *x
	UnOpKind_UN_OP_ARROW       UnOpKind = 7 // <-x
)

// Enum value maps for UnOpKind.
var (
	UnOpKind_name = map[int32]string{
		0: "UN_OP_UNSPECIFIED",
		1: "UN_OP_NOT",
		2: "UN_OP_BIT_NOT",
		3: "UN_OP_NEG",
		4: "UN_OP_POS",
		5: "UN_OP_ADDR",
		6: "UN_OP_DEREF",
		7: "UN_OP_ARROW",
	}
	UnOpKind_value = map[string]int32{
		"UN_OP_UNSPECIFIED": 0,
		"UN_OP_NOT":         1,
		"UN_OP_BIT_NOT":     2,
		"UN_OP_NEG":         3,
		"UN_OP_POS":         4,
		"UN_OP_ADDR":        5,
		"UN_OP_DEREF":       6,
		"UN_OP_ARROW":       7,
	}
)

func (x UnOpKind) Enum() *UnOpKind {
	p := new(UnOpKind)
	*p = x
	return p
}

func (x UnOpKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnOpKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_instruction_proto_enumTypes[2].Descriptor()
}

func (UnOpKind) Type() protoreflect.EnumType {
	return &file_proto_instruction_proto_enumTypes[2]
}

func (x UnOpKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnOpKind.Descriptor instead.
func (UnOpKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_instruction_proto_rawDescGZIP(), []int{2}
}

// Value represents an operand: a register (SSA result), a constant, a global,
// or a direct function reference (by canonical name).
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_RegName
	//	*Value_Constant
	//	*Value_GlobalName
	//	*Value_FuncName
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_instruction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_instruction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_instruction_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetRegName() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_RegName); ok {
			return x.RegName
		}
	}
	return ""
}

func (x *Value) GetConstant() *Constant {
	if x != nil {
		if x, ok := x.Kind.(*Value_Constant); ok {
			return x.Constant
		}
	}
	return nil
}

func (x *Value) GetGlobalName() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_GlobalName); ok {
			return x.GlobalName
		}
	}
	return ""
}

func (x *Value) GetFuncName() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_FuncName); ok {
			return x.FuncName
		}
	}
	return ""
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_RegName struct {
	RegName string `protobuf:"bytes,1,opt,name=reg_name,json=regName,proto3,oneof"` // result of another instruction in this function
}

type Value_Constant struct {
	Constant *Constant `protobuf:"bytes,2,opt,name=constant,proto3,oneof"`
}

type Value_GlobalName struct {
	GlobalName string `protobuf:"bytes,3,opt,name=global_name,json=globalName,proto3,oneof"` // a Global variable by name
}

type Value_FuncName struct {
	FuncName string `protobuf:"bytes,4,opt,name=func_name,json=funcName,proto3,oneof"` // direct function reference (canonical name)
}

func (*Value_RegName) isValue_Kind() {}

func (*Value_Constant) isValue_Kind() {}

func (*Value_GlobalName) isValue_Kind() {}

func (*Value_FuncName) isValue_Kind() {}

// Instruction represents a single SSA instruction.
type Instruction struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Result register name (if any), e.g. "t0". Empty for void.
	Op      OpCode                 `protobuf:"varint,2,opt,name=op,proto3,enum=godzilla.ir.v1.OpCode" json:"op,omitempty"`
	Type    *Type                  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // Result type
	Pos     *Position              `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Comment string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	// Generic operands.
	Operands []*Value `protobuf:"bytes,6,rep,name=operands,proto3" json:"operands,omitempty"`
	// For BIN_OP / UN_OP.
	BinOp BinOpKind `protobuf:"varint,7,opt,name=bin_op,json=binOp,proto3,enum=godzilla.ir.v1.BinOpKind" json:"bin_op,omitempty"`
	UnOp  UnOpKind  `protobuf:"varint,8,opt,name=un_op,json=unOp,proto3,enum=godzilla.ir.v1.UnOpKind" json:"un_op,omitempty"`
	// For FIELD / FIELD_ADDR / EXTRACT (element index).
	FieldIndex int32 `protobuf:"varint,9,opt,name=field_index,json=fieldIndex,proto3" json:"field_index,omitempty"`
	// For CALL / INVOKE, and for call-carrying intrinsics (go.defer, go.goroutine).
	Call *CallCommon `protobuf:"bytes,10,opt,name=call,proto3" json:"call,omitempty"`
	// For PHI: predecessor block ids, parallel to `operands`.
	Blocks []string `protobuf:"bytes,11,rep,name=blocks,proto3" json:"blocks,omitempty"`
	// For IF.
	TrueBlock  string `protobuf:"bytes,12,opt,name=true_block,json=trueBlock,proto3" json:"true_block,omitempty"`
	FalseBlock string `protobuf:"bytes,13,opt,name=false_block,json=falseBlock,proto3" json:"false_block,omitempty"`
	// For JUMP.
	JumpBlock string `protobuf:"bytes,14,opt,name=jump_block,json=jumpBlock,proto3" json:"jump_block,omitempty"`
	// For ALLOC: hint that the allocation escapes to the heap.
	Heap bool `protobuf:"varint,15,opt,name=heap,proto3" json:"heap,omitempty"`
	// For SWITCH.
	Cases []*Case `protobuf:"bytes,17,rep,name=cases,proto3" json:"cases,omitempty"`
	// For OP_CODE_INTRINSIC: the canonical intrinsic name, e.g. "go.chan.send".
	Intrinsic     string `protobuf:"bytes,18,opt,name=intrinsic,proto3" json:"intrinsic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_proto_instruction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_instruction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_proto_instruction_proto_rawDescGZIP(), []int{1}
}

func (x *Instruction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instruction) GetOp() OpCode {
	if x != nil {
		return x.Op
	}
	return OpCode_OP_CODE_UNSPECIFIED
}

func (x *Instruction) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Instruction) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Instruction) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Instruction) GetOperands() []*Value {
	if x != nil {
		return x.Operands
	}
	return nil
}

func (x *Instruction) GetBinOp() BinOpKind {
	if x != nil {
		return x.BinOp
	}
	return BinOpKind_BIN_OP_UNSPECIFIED
}

func (x *Instruction) GetUnOp() UnOpKind {
	if x != nil {
		return x.UnOp
	}
	return UnOpKind_UN_OP_UNSPECIFIED
}

func (x *Instruction) GetFieldIndex() int32 {
	if x != nil {
		return x.FieldIndex
	}
	return 0
}

func (x *Instruction) GetCall() *CallCommon {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *Instruction) GetBlocks() []string {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Instruction) GetTrueBlock() string {
	if x != nil {
		return x.TrueBlock
	}
	return ""
}

func (x *Instruction) GetFalseBlock() string {
	if x != nil {
		return x.FalseBlock
	}
	return ""
}

func (x *Instruction) GetJumpBlock() string {
	if x != nil {
		return x.JumpBlock
	}
	return ""
}

func (x *Instruction) GetHeap() bool {
	if x != nil {
		return x.Heap
	}
	return false
}

func (x *Instruction) GetCases() []*Case {
	if x != nil {
		return x.Cases
	}
	return nil
}

func (x *Instruction) GetIntrinsic() string {
	if x != nil {
		return x.Intrinsic
	}
	return ""
}

type Case struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Value                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // Case value (constant)
	Block         string                 `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"` // Target block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Case) Reset() {
	*x = Case{}
	mi := &file_proto_instruction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_proto_instruction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_proto_instruction_proto_rawDescGZIP(), []int{2}
}

func (x *Case) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Case) GetBlock() string {
	if x != nil {
		return x.Block
	}
	return ""
}

type CallCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Value                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // Function to call (func_name for static, receiver reg for invoke)
	Args          []*Value               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	IsInvoke      bool                   `protobuf:"varint,3,opt,name=is_invoke,json=isInvoke,proto3" json:"is_invoke,omitempty"`      // True if dynamic dispatch (interface method)
	MethodName    string                 `protobuf:"bytes,4,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"` // Only for is_invoke=true
	Callee        string                 `protobuf:"bytes,5,opt,name=callee,proto3" json:"callee,omitempty"`                           // Resolved canonical callee name when statically known
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCommon) Reset() {
	*x = CallCommon{}
	mi := &file_proto_instruction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCommon) ProtoMessage() {}

func (x *CallCommon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_instruction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCommon.ProtoReflect.Descriptor instead.
func (*CallCommon) Descriptor() ([]byte, []int) {
	return file_proto_instruction_proto_rawDescGZIP(), []int{3}
}

func (x *CallCommon) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CallCommon) GetArgs() []*Value {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CallCommon) GetIsInvoke() bool {
	if x != nil {
		return x.IsInvoke
	}
	return false
}

func (x *CallCommon) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *CallCommon) GetCallee() string {
	if x != nil {
		return x.Callee
	}
	return ""
}

var File_proto_instruction_proto protoreflect.FileDescriptor

const file_proto_instruction_proto_rawDesc = "" +
	"\n" +
	"\x17proto/instruction.proto\x12\x0egodzilla.ir.v1\x1a\x12proto/common.proto\"\xa6\x01\n" +
	"\x05Value\x12\x1b\n" +
	"\breg_name\x18\x01 \x01(\tH\x00R\aregName\x126\n" +
	"\bconstant\x18\x02 \x01(\v2\x18.godzilla.ir.v1.ConstantH\x00R\bconstant\x12!\n" +
	"\vglobal_name\x18\x03 \x01(\tH\x00R\n" +
	"globalName\x12\x1d\n" +
	"\tfunc_name\x18\x04 \x01(\tH\x00R\bfuncNameB\x06\n" +
	"\x04kind\"\xf9\x04\n" +
	"\vInstruction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x02op\x18\x02 \x01(\x0e2\x16.godzilla.ir.v1.OpCodeR\x02op\x12(\n" +
	"\x04type\x18\x03 \x01(\v2\x14.godzilla.ir.v1.TypeR\x04type\x12*\n" +
	"\x03pos\x18\x04 \x01(\v2\x18.godzilla.ir.v1.PositionR\x03pos\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x121\n" +
	"\boperands\x18\x06 \x03(\v2\x15.godzilla.ir.v1.ValueR\boperands\x120\n" +
	"\x06bin_op\x18\a \x01(\x0e2\x19.godzilla.ir.v1.BinOpKindR\x05binOp\x12-\n" +
	"\x05un_op\x18\b \x01(\x0e2\x18.godzilla.ir.v1.UnOpKindR\x04unOp\x12\x1f\n" +
	"\vfield_index\x18\t \x01(\x05R\n" +
	"fieldIndex\x12.\n" +
	"\x04call\x18\n" +
	" \x01(\v2\x1a.godzilla.ir.v1.CallCommonR\x04call\x12\x16\n" +
	"\x06blocks\x18\v \x03(\tR\x06blocks\x12\x1d\n" +
	"\n" +
	"true_block\x18\f \x01(\tR\ttrueBlock\x12\x1f\n" +
	"\vfalse_block\x18\r \x01(\tR\n" +
	"falseBlock\x12\x1d\n" +
	"\n" +
	"jump_block\x18\x0e \x01(\tR\tjumpBlock\x12\x12\n" +
	"\x04heap\x18\x0f \x01(\bR\x04heap\x12*\n" +
	"\x05cases\x18\x11 \x03(\v2\x14.godzilla.ir.v1.CaseR\x05cases\x12\x1c\n" +
	"\tintrinsic\x18\x12 \x01(\tR\tintrinsicJ\x04\b\x10\x10\x11\"I\n" +
	"\x04Case\x12+\n" +
	"\x05value\x18\x01 \x01(\v2\x15.godzilla.ir.v1.ValueR\x05value\x12\x14\n" +
	"\x05block\x18\x02 \x01(\tR\x05block\"\xba\x01\n" +
	"\n" +
	"CallCommon\x12+\n" +
	"\x05value\x18\x01 \x01(\v2\x15.godzilla.ir.v1.ValueR\x05value\x12)\n" +
	"\x04args\x18\x02 \x03(\v2\x15.godzilla.ir.v1.ValueR\x04args\x12\x1b\n" +
	"\tis_invoke\x18\x03 \x01(\bR\bisInvoke\x12\x1f\n" +
	"\vmethod_name\x18\x04 \x01(\tR\n" +
	"methodName\x12\x16\n" +
	"\x06callee\x18\x05 \x01(\tR\x06callee*\xf6\x03\n" +
	"\x06OpCode\x12\x17\n" +
	"\x13OP_CODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOP_CODE_RET\x10\x01\x12\x10\n" +
	"\fOP_CODE_JUMP\x10\x02\x12\x0e\n" +
	"\n" +
	"OP_CODE_IF\x10\x03\x12\x12\n" +
	"\x0eOP_CODE_SWITCH\x10\x04\x12\x11\n" +
	"\rOP_CODE_PANIC\x10\x05\x12\x17\n" +
	"\x13OP_CODE_UNREACHABLE\x10\x06\x12\x11\n" +
	"\rOP_CODE_ALLOC\x10\n" +
	"\x12\x10\n" +
	"\fOP_CODE_LOAD\x10\v\x12\x11\n" +
	"\rOP_CODE_STORE\x10\f\x12\x11\n" +
	"\rOP_CODE_FIELD\x10\r\x12\x16\n" +
	"\x12OP_CODE_FIELD_ADDR\x10\x0e\x12\x11\n" +
	"\rOP_CODE_INDEX\x10\x0f\x12\x16\n" +
	"\x12OP_CODE_INDEX_ADDR\x10\x10\x12\x12\n" +
	"\x0eOP_CODE_BIN_OP\x10\x14\x12\x11\n" +
	"\rOP_CODE_UN_OP\x10\x15\x12\x0f\n" +
	"\vOP_CODE_PHI\x10\x16\x12\x10\n" +
	"\fOP_CODE_CALL\x10\x1e\x12\x12\n" +
	"\x0eOP_CODE_INVOKE\x10\x1f\x12\x13\n" +
	"\x0fOP_CODE_CONVERT\x10(\x12\x17\n" +
	"\x13OP_CODE_TYPE_ASSERT\x10)\x12\x1a\n" +
	"\x16OP_CODE_MAKE_INTERFACE\x10*\x12\x13\n" +
	"\x0fOP_CODE_EXTRACT\x10+\x12\x15\n" +
	"\x11OP_CODE_INTRINSIC\x102*\xb6\x02\n" +
	"\tBinOpKind\x12\x16\n" +
	"\x12BIN_OP_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"BIN_OP_ADD\x10\x01\x12\x0e\n" +
	"\n" +
	"BIN_OP_SUB\x10\x02\x12\x0e\n" +
	"\n" +
	"BIN_OP_MUL\x10\x03\x12\x0e\n" +
	"\n" +
	"BIN_OP_QUO\x10\x04\x12\x0e\n" +
	"\n" +
	"BIN_OP_REM\x10\x05\x12\x0e\n" +
	"\n" +
	"BIN_OP_AND\x10\x06\x12\r\n" +
	"\tBIN_OP_OR\x10\a\x12\x0e\n" +
	"\n" +
	"BIN_OP_XOR\x10\b\x12\x0e\n" +
	"\n" +
	"BIN_OP_SHL\x10\t\x12\x0e\n" +
	"\n" +
	"BIN_OP_SHR\x10\n" +
	"\x12\x12\n" +
	"\x0eBIN_OP_AND_NOT\x10\v\x12\x0e\n" +
	"\n" +
	"BIN_OP_EQL\x10\f\x12\x0e\n" +
	"\n" +
	"BIN_OP_NEQ\x10\r\x12\x0e\n" +
	"\n" +
	"BIN_OP_LSS\x10\x0e\x12\x0e\n" +
	"\n" +
	"BIN_OP_LEQ\x10\x0f\x12\x0e\n" +
	"\n" +
	"BIN_OP_GTR\x10\x10\x12\x0e\n" +
	"\n" +
	"BIN_OP_GEQ\x10\x11*\x93\x01\n" +
	"\bUnOpKind\x12\x15\n" +
	"\x11UN_OP_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tUN_OP_NOT\x10\x01\x12\x11\n" +
	"\rUN_OP_BIT_NOT\x10\x02\x12\r\n" +
	"\tUN_OP_NEG\x10\x03\x12\r\n" +
	"\tUN_OP_POS\x10\x04\x12\x0e\n" +
	"\n" +
	"UN_OP_ADDR\x10\x05\x12\x0f\n" +
	"\vUN_OP_DEREF\x10\x06\x12\x0f\n" +
	"\vUN_OP_ARROW\x10\aB\x17Z\x15godzilla/pkg/ir/v1;irb\x06proto3"

var (
	file_proto_instruction_proto_rawDescOnce sync.Once
	file_proto_instruction_proto_rawDescData []byte
)

func file_proto_instruction_proto_rawDescGZIP() []byte {
	file_proto_instruction_proto_rawDescOnce.Do(func() {
		file_proto_instruction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_instruction_proto_rawDesc), len(file_proto_instruction_proto_rawDesc)))
	})
	return file_proto_instruction_proto_rawDescData
}

var file_proto_instruction_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_instruction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_instruction_proto_goTypes = []any{
	(OpCode)(0),         // 0: godzilla.ir.v1.OpCode
	(BinOpKind)(0),      // 1: godzilla.ir.v1.BinOpKind
	(UnOpKind)(0),       // 2: godzilla.ir.v1.UnOpKind
	(*Value)(nil),       // 3: godzilla.ir.v1.Value
	(*Instruction)(nil), // 4: godzilla.ir.v1.Instruction
	(*Case)(nil),        // 5: godzilla.ir.v1.Case
	(*CallCommon)(nil),  // 6: godzilla.ir.v1.CallCommon
	(*Constant)(nil),    // 7: godzilla.ir.v1.Constant
	(*Type)(nil),        // 8: godzilla.ir.v1.Type
	(*Position)(nil),    // 9: godzilla.ir.v1.Position
}
var file_proto_instruction_proto_depIdxs = []int32{
	7,  // 0: godzilla.ir.v1.Value.constant:type_name -> godzilla.ir.v1.Constant
	0,  // 1: godzilla.ir.v1.Instruction.op:type_name -> godzilla.ir.v1.OpCode
	8,  // 2: godzilla.ir.v1.Instruction.type:type_name -> godzilla.ir.v1.Type
	9,  // 3: godzilla.ir.v1.Instruction.pos:type_name -> godzilla.ir.v1.Position
	3,  // 4: godzilla.ir.v1.Instruction.operands:type_name -> godzilla.ir.v1.Value
	1,  // 5: godzilla.ir.v1.Instruction.bin_op:type_name -> godzilla.ir.v1.BinOpKind
	2,  // 6: godzilla.ir.v1.Instruction.un_op:type_name -> godzilla.ir.v1.UnOpKind
	6,  // 7: godzilla.ir.v1.Instruction.call:type_name -> godzilla.ir.v1.CallCommon
	5,  // 8: godzilla.ir.v1.Instruction.cases:type_name -> godzilla.ir.v1.Case
	3,  // 9: godzilla.ir.v1.Case.value:type_name -> godzilla.ir.v1.Value
	3,  // 10: godzilla.ir.v1.CallCommon.value:type_name -> godzilla.ir.v1.Value
	3,  // 11: godzilla.ir.v1.CallCommon.args:type_name -> godzilla.ir.v1.Value
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_instruction_proto_init() }
func file_proto_instruction_proto_init() {
	if File_proto_instruction_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_instruction_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_RegName)(nil),
		(*Value_Constant)(nil),
		(*Value_GlobalName)(nil),
		(*Value_FuncName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_instruction_proto_rawDesc), len(file_proto_instruction_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_instruction_proto_goTypes,
		DependencyIndexes: file_proto_instruction_proto_depIdxs,
		EnumInfos:         file_proto_instruction_proto_enumTypes,
		MessageInfos:      file_proto_instruction_proto_msgTypes,
	}.Build()
	File_proto_instruction_proto = out.File
	file_proto_instruction_proto_goTypes = nil
	file_proto_instruction_proto_depIdxs = nil
}
