// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/module.proto

package ir

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Module represents a compilation unit (e.g. Go package).
type Module struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`           // Package path/name
	Functions []*Function            `protobuf:"bytes,2,rep,name=functions,proto3" json:"functions,omitempty"` // All functions (methods, init, main)
	Types     []*Type                `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`         // Named types defined in this module
	Globals   []*Global              `protobuf:"bytes,4,rep,name=globals,proto3" json:"globals,omitempty"`     // Global variables
	// Dependency information
	Imports []string `protobuf:"bytes,5,rep,name=imports,proto3" json:"imports,omitempty"` // Imported module names/paths
	// Source language that produced this module: "go", "python", "javascript".
	Language      string `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_proto_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_proto_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_proto_module_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Module) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Module) GetGlobals() []*Global {
	if x != nil {
		return x.Globals
	}
	return nil
}

func (x *Module) GetImports() []string {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *Module) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Program represents the entire application (multiple modules).
type Program struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	MainPkg       *Function              `protobuf:"bytes,2,opt,name=main_pkg,json=mainPkg,proto3" json:"main_pkg,omitempty"` // Entry point package/function
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`                      // e.g., "ssa", "source"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Program) Reset() {
	*x = Program{}
	mi := &file_proto_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_proto_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_proto_module_proto_rawDescGZIP(), []int{1}
}

func (x *Program) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *Program) GetMainPkg() *Function {
	if x != nil {
		return x.MainPkg
	}
	return nil
}

func (x *Program) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

var File_proto_module_proto protoreflect.FileDescriptor

const file_proto_module_proto_rawDesc = "" +
	"\n" +
	"\x12proto/module.proto\x12\x0egodzilla.ir.v1\x1a\x12proto/common.proto\x1a\x14proto/function.proto\"\xe8\x01\n" +
	"\x06Module\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\tfunctions\x18\x02 \x03(\v2\x18.godzilla.ir.v1.FunctionR\tfunctions\x12*\n" +
	"\x05types\x18\x03 \x03(\v2\x14.godzilla.ir.v1.TypeR\x05types\x120\n" +
	"\aglobals\x18\x04 \x03(\v2\x16.godzilla.ir.v1.GlobalR\aglobals\x12\x18\n" +
	"\aimports\x18\x05 \x03(\tR\aimports\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\"\x84\x01\n" +
	"\aProgram\x120\n" +
	"\amodules\x18\x01 \x03(\v2\x16.godzilla.ir.v1.ModuleR\amodules\x123\n" +
	"\bmain_pkg\x18\x02 \x01(\v2\x18.godzilla.ir.v1.FunctionR\amainPkg\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04modeB\x17Z\x15godzilla/pkg/ir/v1;irb\x06proto3"

var (
	file_proto_module_proto_rawDescOnce sync.Once
	file_proto_module_proto_rawDescData []byte
)

func file_proto_module_proto_rawDescGZIP() []byte {
	file_proto_module_proto_rawDescOnce.Do(func() {
		file_proto_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_module_proto_rawDesc), len(file_proto_module_proto_rawDesc)))
	})
	return file_proto_module_proto_rawDescData
}

var file_proto_module_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_module_proto_goTypes = []any{
	(*Module)(nil),   // 0: godzilla.ir.v1.Module
	(*Program)(nil),  // 1: godzilla.ir.v1.Program
	(*Function)(nil), // 2: godzilla.ir.v1.Function
	(*Type)(nil),     // 3: godzilla.ir.v1.Type
	(*Global)(nil),   // 4: godzilla.ir.v1.Global
}
var file_proto_module_proto_depIdxs = []int32{
	2, // 0: godzilla.ir.v1.Module.functions:type_name -> godzilla.ir.v1.Function
	3, // 1: godzilla.ir.v1.Module.types:type_name -> godzilla.ir.v1.Type
	4, // 2: godzilla.ir.v1.Module.globals:type_name -> godzilla.ir.v1.Global
	0, // 3: godzilla.ir.v1.Program.modules:type_name -> godzilla.ir.v1.Module
	2, // 4: godzilla.ir.v1.Program.main_pkg:type_name -> godzilla.ir.v1.Function
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_module_proto_init() }
func file_proto_module_proto_init() {
	if File_proto_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_function_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_module_proto_rawDesc), len(file_proto_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_module_proto_goTypes,
		DependencyIndexes: file_proto_module_proto_depIdxs,
		MessageInfos:      file_proto_module_proto_msgTypes,
	}.Build()
	File_proto_module_proto = out.File
	file_proto_module_proto_goTypes = nil
	file_proto_module_proto_depIdxs = nil
}
